### ISSUE TITLE
ROT: navigation/rateOfTurn seems not correctly parsed from NMEA AIVDM

### ISSUE THREAD

**Issue by Hakansv** [SignalK/signalk-server#1116] opened 2020-09-06 09:07 UTC
AIVDM messages where a rate of turn info is available are not creating navigation/rateOfTurn out to the SK connection.
Setup:
AIS NMEA0183 is flowing into SK by UDP port 10112.
Connection to the SK server by OCPN can be done either using a TCP or a Signal K connection.

If I connect the TCP way ROT for a specific target is shown.
If I connect the Signal K way no ROT for the same target is received.
When using the "Data Browser" on the SK server for the same target no navigation.rateOfTurn path can be found.

So I get the impression the rate of turn info is not properly parsed from the NMEA AIVDM message.

Håkan

**Comment by tkurki** [comment] 2020-09-06 09:44
Yep. Can you add an issue at https://github.com/SignalK/nmea0183-signalk/issues/new and it would be great if you could include sample sentences with the issue, much quicker to implement then.

Closing this as the issue is really in the parser.

**Closed by tkurki** 2020-09-06 09:44 UTC
