### ISSUE TITLE
NMEA 0183 tcp and SignalK tcp servers should protect itself from dead or slow clients 

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-server#1564] opened 2023-05-28 17:33 UTC
NMEA 0183 tcp and SignalK tcp servers should protect itself from dead or slow clients.

there is no currently 
analog of ‘no data timeout’ like on tcp providers side in

tcp.ts or nmea-tcp.ts server code. 

Bad clients, powered off clients can seriously degrade SignalK by not closing tcp connection. Slow readers as well.

**Comment by mgrouch** [comment] 2023-05-28 17:39
Related:

https://github.com/SignalK/signalk-server/pull/698

**Comment by mgrouch** [comment] 2023-05-28 18:16
For slow readers a leaky bucket algorithm can be employed. To still deliver up to date data with lower rate. 

https://en.m.wikipedia.org/wiki/Leaky_bucket

**Comment by tkurki** [comment] 2024-01-22 17:21
Duplicate of #1055

**Closed by tkurki** 2024-01-22 17:21 UTC
