### ISSUE TITLE
Saving plugin settings failed

### ISSUE THREAD

**Issue by AaskovKnudsen** [SignalK/signalk-server#1697] opened 2024-03-10 19:06 UTC
After upgrading signalk from 2.3.0 to 2.6.1, I get this error message when saving changes in several plugins:
"Saving plugin settings failed"
For instance this plugin:
"N2K AIS to NMEA0183"

Thanks for helping
Jan

**Comment by tkurki** [comment] 2024-03-10 19:10
Any error messages on the server log?

**Comment by AaskovKnudsen** [comment] 2024-03-10 22:52
No messages in the server log as far as I can see.
My installation is RPI4 openplotter headless image.
I made 3 images to show my issue.
1: select plugin config
2: select configure "N2K AIS to NMEA0183" and press Submit
3: shows my problem "Saving plugin settings failed
Same thing happens with some other plugins, but not all.
Hope this helps.
/jan

![1](https://github.com/SignalK/signalk-server/assets/150262992/1ef59c6d-b643-4946-a561-74e524e6612f)
![2](https://github.com/SignalK/signalk-server/assets/150262992/6e80ad9a-42a1-4063-a5b2-86a06369317f)
![3](https://github.com/SignalK/signalk-server/assets/150262992/3d532ec1-e917-45e1-8f2c-dd997c993b3b)

**Comment by kdt179** [comment] 2024-03-11 19:39
I too have discovered this problem.  Occurs with several of the preinstalled plugins, and at least the one installed plugin from the app store I needed (signal-to-influxdb2). Happy to provide additional information - just let me know how I can help.  

Is it possible to install a previous version? Are there instructions somewhere for how to do that (using Windows and Windows installer)? 

Many thanks.

-Ken

**Comment by caspartfg** [comment] 2024-03-11 21:21
Just to add I also have the same issue - RPi4. I thought it was something i'd done, so blew away the install... However the problem still persists v.2.6.1.   Wasn't there on the previous version.  thx

**Comment by caspartfg** [comment] 2024-03-11 21:46
Just to add, i've reverted back to 2.6.0 and the problem is resolved, so it seems like it's linked to 2.6.1

**Comment by kdt179** [comment] 2024-03-13 23:49
Thank you for the update! Awesome!

**Comment by tkurki** [comment] 2024-03-17 09:45
Fixed in [2.6.2](https://github.com/SignalK/signalk-server/releases/tag/v2.6.2).

**Closed by tkurki** 2024-03-17 09:45 UTC
