### ISSUE TITLE
Web interface stops responding

### ISSUE THREAD

**Issue by TensionSoftware** [SignalK/signalk-server#1111] opened 2020-08-28 21:57 UTC
I have been running my Signalk server for more than a year pretty successfully but am now running into an issue where the web interface stops responding.

This is running on a Raspberry Pi 4 4GB via a USB SSD using USB boot.
I have nodered embedded and use that a fair bit to capture data from several different serial devices. I have approximately 600 datapoints at any given time and on the order of 30-50 deltas per second. This has all worked pretty well for a long time. I periodically make various changes to improve things but cannot pin point any specific change that may have caused this.

I recently decided to update the server to the newest version in hopes that it would help but it did not seem to change.

When I start the server everything comes up and seems to work most of the time. Sometimes the web interface responds for the first few minutes after boot but then stops responding or starts responding extremely slowly (30 seconds or more to load the dashboard).

If it starts and runs it will sometimes run well for a few hours to as much as a few days before it stops. I am collecting datapoints into an InfluxDB so I can see the moment when it appears to stop. 

Everything else on the Pi continues to work. 

I have checked the SYSLOG and DMESG and there does not appear to be any indication as to why it failed. It is as if it just stops or slows down significantly. I have disabled all plugins which seems to help for a while but it still eventually fails. I have also tried disconnecting the serial devices which again made it last longer but still eventually failed.

I noticed that there is a process called node that is obviously the SignalK server because it is the one that closes when I reset the server. This process will change in the amount of CPU it uses from 1-2% up to 60-70% when working correctly. Once it stops responding this process shows 25% and pretty much stays at the level. It is almost as if something is binding up the server but I am not sure how to further troubleshoot it since there is no log events giving me any hints.

I did see some events MaxListenersExceededWarning: Possible EventEmitter memory leak detected messages a few times after the server had stopped responding. 

Suggestions for how to proceed would be appreciated.

**Comment by tkurki** [comment] 2020-08-30 16:22
Some questions to help understand what's going on
- I assume you are talking about the server adming interface (the webapps are technically different from the admin ui)
- when you say "web interface stops responding" what exactly is happening?  it no longer loads(if not does it just stop from loading, or any error messages?) / lose server connection (shows an error message) / dashboard figures stop updating
- does your server work in any meaningful measure without your node-red flows? if yes have you tried running without the node-red plugin (not enabled)?
- can you load  your server's /signalk/v1/api/ endpoint? anything unexpected there?
- you said you can tell from InfluxDb when the server slows down. So this is really about the server stopping working or slowing down, not about the admin ui no longer working?

Yes, the server is a Node.js application and the process shows as node. I assume you've used `top` when checking the cpu usage. What does the process's memory consumption look like?

I am surprised that cpu stays at 25%. Most problems I can think of would result in 100% cpu usage.

You can add logging about memory usage by adding ` --trace_gc` where node is started in the file `signalk-server` https://github.com/SignalK/signalk-server/blob/master/bin/signalk-server#L1  - I think you can find that file's location in the file $HOME/.signalk/signalk-server.

Sounds like the problem is not predictable and so reproducing it is not simple.

Can you capture your server's data into a log file? I think it should work with node-red generated data if you turn on data logging with `Enable logging` in the plugin configuration. I am thinking of replaying a data file and being able to reproduce the problem that way.

**Comment by TensionSoftware** [comment] 2020-08-31 13:36
Thank you for assisting me with this issue. Here are the answers to your questions in order.

- Yes I am talking about the admin UI. 

- When this issue occurs, if I attempt to connect to the admin UI I it will act as if it is connecting but not receiving data very quickly. Typically, after several minutes it will either timeout. In some cases it will display parts of the admin UI.

- My server does have a GPS device with 7 deltas per second that is not part of NodeRed. I started a test yesterday with the NodeRed Embedded plugin disabled completely and all seems well today. This tells me it could either be NodeRed related or it has something to do with having 600 datapoints and more deltas. 

- I had not yet thought of trying to load  /signalk/v1/api/ endpoint. I will reconfigure the server back to normal and try this once it stops responding.

- Yes it appears the whole server is not responding or more likely responding very slowly. It does look like the admin UI is trying to load and not just giving a 404 error so it is finding the endpoint but it often times out or only loads a small amount of the data before timing out. Also, upon further inspection it looks like the influxdb writer still is writing out messages but at a much slower rate. It should be writing data very frequently but will reduce to one message every couple of minutes. This would suggest the server is still doing work but is being slowed by something.

I will check on the exact memory consumption the next time it fails and post back but it is certainly more than it normal operates at. I believe it is at least double by the time I restart which is usually only as much a few hours after this happens.

I agree that 25% seems to be an odd amount of CPU usage. That has really caught my attention. I am not sure how or why it would sit about there and perhaps it has little to do with this issue but that is pretty consistent.

I will attempt to capture the logging and attach once I have run it to a point where it happens again.

Thank you

**Comment by tkurki** [comment] 2020-08-31 14:32
Capture /signalk/v1/api/  also when it is running ok, as it may be too late after the admin ui stops loading.

**Comment by tkurki** [comment] 2020-08-31 20:13
Have you tried tweaking the influxdb plugin parameters? Or running without it, but with full data volume?

Logging the data and importing it offline in batches is technically an option.

If it is feasible and you are comfortable with it arranging remote access for me for troubleshooting is an option. In that case contact me in Signal K Slack.

**Comment by TensionSoftware** [comment] 2020-08-31 22:20
I ran it to the point of failure and it took most of the day.

This time when I checked on CPU usage and memory I found that kplex seemed to be using more CPU than normal (~15%). This seemed odd so I shutdown the kplex server and suddenly the SignalK server started working normally. I am going to leave the kplex server off for a while to see if that is the root of the issue somehow. My kplex server handles data both to and from the signalk server so perhaps I am somehow looping back into the server and causing it to have to work too hard? It would have to be something that is incrementally increasing since it does not cause the issue immediately in most cases. 

The memory did not change significantly like I had originally thought. It only increased by about 60MB but was fairly stable at that point. /signalk/v1/api/ responds much the same as the admin UI. It looks as if it must be there but sending data extremely slowly and eventually times out. 

As for Influx, I have completely disabled output to Influx and still had the issue eventually. This run did not have Influx disabled.

Unfortunately, remote access would not be easily possible given my current network setup but I greatly appreciate the offer.

Attached is apiOutput.txt which I captured not long after the server started and stabilized
Also attached is the log file from when it stopped responding. I have several other log files for the day so let me know if those would be useful however they total 140MB. 

[skserver-raw_2020-08-31T18.log](https://github.com/SignalK/signalk-server/files/5152862/skserver-raw_2020-08-31T18.log)
. 

[apiOutput.txt](https://github.com/SignalK/signalk-server/files/5152859/apiOutput.txt)

**Comment by TensionSoftware** [comment] 2020-08-31 22:33
Looking deeper into the kplex server I am not sure why this is happening. So far today the Signalk server has been outputting to the kplex server but the kplex server has had nothing to send back to Signalk. None of the devices that attach via kplex were connected all day so no deltas were created from the kplex connection.

That makes me think that it is just something in the output to the kplex server and stopping it maybe had some impact on breaking the cycle is was stuck in. Thoughts?

Here is my kplex.conf

[tcp]
name=tosk
direction=out
mode=server
port=30330
ofilter=+AGRSA:+HCHDG:+VM***:+WI***:-all

[tcp]
name=signalkdepth
direction=out
mode=server
port=30333
ofilter=+SDDPT:-all

[udp]
name=miniplexIn
device=eth0
direction=in
port=10110
ifilter=+AGRSA:+WIMWV:+WIMDA:+HCHDG:+SDDPT:+VWVHW:+VWVLW:+WIMTW:-all

[udp]
name=miniplexOut
address=192.168.100.105
device=eth0
direction=out
port=10110
ofilter=-SDDPT

[tcp]
name=navionicsoutput
mode=server
direction=out
port=2000
ofilter=-SDDPT

[tcp]
name=fromsk
direction=in
mode=client
persist=yes
retry=10
address=192.168.100.125
port=10110
ifilter=-AGRSA:-HCHDG:-AP***:-WI***:-VM***:-VW***:-SDDPT:-MXSTN

**Comment by TensionSoftware** [comment] 2020-09-01 14:39
16 hours now and still no issue as long as the kplex server is disabled. Any thoughts on what could be causing this?

**Comment by tkurki** [comment] 2020-09-01 16:18
We had previously issues with a ws client that was not reading the stream and the server kept buffering the data, grinding eventually to a halt. This does not seem similar, if the memory footprint does not increase.

Anything in kplex log? Is the network wired or wireless?

**Comment by TensionSoftware** [comment] 2020-09-01 16:28
I have not yet used logging on the Kplex server so I will see if I can get that configured and see what comes of it. 

The connection is wired but the kplex server is on the same Raspberry Pi so it is a localhost connection and for the present testing it has nothing else connected externally.

**Comment by TensionSoftware** [comment] 2020-09-02 13:29
Now after several hours with Kplex running again I am seeing the issue again in the SignalK server.

The Kplex server is giving me these output messages repeating very rapidly:
kplex DEBUG: Dropped senblk q=(unknown)
kplex DEBUG: Dropped senblk q=signalkdepth
kplex DEBUG: Dropped senblk q=tosk
kplex DEBUG: Dropped senblk q=miniplexOut

**Comment by stripydog** [comment] 2020-09-02 14:09
This might well be a data loop.  kplex queues message for output in a linked list of a fixed (but configurable) size which acts as a buffer and will drop the oldest message if it fills the queue to add a new sentence to the back: that's when those debug messages are generated.  Note to self: q=(unknown) is probably the queue for input to the multiplexing engine: should make that more explicit :-).  The fromsk/tosk interfaces seem to be complimentary in that what is output is filtered on input so I'd be looking at a loop involving the miniplex.  An option to see where all the data is coming from might be to add a log file and specify src tags:
[file]
filename=/tmp/logfile
srctag=input
qsize=128
direction=out


Note that increasing qsize for all your outputs almost certainly isn't the answer as it'll only delay the inevitable.  Also that using bidirectional interfaces avoids data loops with a single endpoint because kplex doesn't write back to an interface it just read from unless you explicitly tell it to

**Comment by TensionSoftware** [comment] 2020-09-02 14:26
Thanks for the feedback.

For the tests I have been performing thus far the kplex server only has the signalk server connected. The Miniplex is powered off so not able to send or receive data. 

I would not that I have tosk as a means to send data back to the signalk server (specifically from the miniplex) but also have the signalkdepth interface which also connects and send to signalk but specifically only for the message SDDPT. I did this because when using only the tosk interface my SDDPT message seemed to be getting dropped somehow. When I changed to having it port through its own interface it started sending every message. This is a side note since the miniplex isnt connected there is no SDDPT message.

**Comment by TensionSoftware** [comment] 2020-09-02 14:41
Quick update, I have been running kplex with a logfile and it looks like the only device inputting data is fromsk and all of those messages should be getting dropped on the tosk and signalkdepth interface based on the filter leaving only the miniplexOut UDP output and the navionicsoutput TCP output, both of which do not have a device connected.

**Comment by stripydog** [comment] 2020-09-02 15:11
Make sure those filters aren't buggy then :-).  try connecting to the servers and checking that there's no output, ie not he command line where you're running kplex:
kplex -f- file: tcp:address=127.0.0.1,port=30330
...and the same for 10110 and 2000
You shouldn't see any output if I understand your current setup correctly
Might also be worth doing:
tcpdump -i eth0 udp port 10110
...just to check there's no bug which has caused kplex to broadcast rather than unicast to the miniplex (and therefore broadcasting to everything else, although the specification of a unicast address should make output unicast (plus I've just tried it and it works as expected)

**Comment by TensionSoftware** [comment] 2020-09-02 15:44
I just checked the output from 127.0.0.1:3000 and there is no data outputting so that appears as it should. As of right now this is the only device connected as it's the feedback to the signalk server. I would expect this to have no output since it should be filtering out everything the signalk server is sending in.

The port 2000 TCP interface is meant specifically for a Navionics tablet to connect and capture data and the only thing that should be filtered out is the SDDPT data. When I test this it appears to be sending data as expected but for the tests over the last few days nothing has been connected to this port.

The UDP 10110 is also sending out everything except SDDPT but only to 192.168.100.105 when it is connected. When I connect to UDP 10110 with something other than IP 192.168.100.105 it does not have any output which is what I expect to be happening. I have not had .105 connected during any of the tests over the last few days either.

**Comment by stripydog** [comment] 2020-09-02 18:12
Would I be right in thinking that while you've been doing these checks it's all been working fine?  If so maybe leave it running and logging to a file until it starts to go crazy again and then take a look at what's in the log file?

**Comment by TensionSoftware** [comment] 2020-09-02 18:16
Yes you are correct that it is working as expected right now and all seems well. It will likely be late this evening or tomorrow sometime before it start having issues again and I will run through all of these checks again. Also, I have had that [file] interface outputting to a log file since I restarted. 

I will let you know the result of the same tests when it starts acting up again.

**Comment by TensionSoftware** [comment] 2020-09-02 22:15
The server slowed down again so I checked the outputs that I had tested before and found that I was seeing a repeated message of !A which is part of an AIS message. My NodeRed setup is reading AIS messages from a serial device and outputting them to nmea0183out which sends them to Kplex. The feedback to SignalK (tosk) should be filtering !A messages based on ofilter=+AGRSA:+HCHDG:+VM***:+WI***:-all but it looks like somehow it is getting sent out anyway which then feeds back to Kplex via the fromsk interface. 

Is it possible this has something to do with the fact that it starts with ! instead of $? Or possibly because the message is obviously missing the rest of the data?

**Comment by stripydog** [comment] 2020-09-03 07:35
The problem is that kplex doesn't check the length of the talker id/ sentence which is normally 5 characters (excluding the starter character) but might not be in the case of proprietary sentences.  Given we're all working from secondary sources that's not inherently wrong but if you can't then filter the resulting sentences passing through, that's obviously a bug, I'll log it as such and fix it.

As a workaround...does this !A have a checksum attached?  If not you can enforce checksum checking which would discard it on input, ie in fromsk:
checksum=yes

I'll copy the kplex issue here for you to track when I've logged it

**Comment by tkurki** [comment] 2020-09-03 07:38
Just add a link to this there/that here in the issue's description or comment, github will turn it into a link.

**Comment by stripydog** [comment] 2020-09-03 07:47
[](https://github.com/stripydog/kplex/issues/39)

**Comment by stripydog** [comment] 2020-09-03 10:58
@TensionSoftware this should be fixed in the "shorts" branch of the kplex repository if you want to check that out, compile it and give it a go.  If you can confirm it addresses the problem to your satisfaction I'll merge it into the develop branch.https://github.com/stripydog/kplex/tree/shorts

**Comment by TensionSoftware** [comment] 2020-09-03 15:12
@tkurki - Based on what we have found this is not specifically an issue with SignalK but instead an issue with data being looped back to SignalK very rapidly. I do not really see anything that you can take away from this issue. I am inclined to close it but thought I would ask, is there anything else you would like to know?

**Comment by stripydog** [comment] 2020-09-03 15:34
Is there not still the question of why the server is putting out "!A".  Does it have a checksum attached, ie is it "!A" or "!A*41"?

**Comment by tkurki** [comment] 2020-09-03 15:38
All done here I think. One more lesson in _data loops are devious_.

Except for sharing the idea that if the malformed data originates from your node-red flows you could probably easily stop it ever entering further into your setup.

**Comment by TensionSoftware** [comment] 2020-09-03 15:39
I apologize for not having answered that. The !A message is all that it is getting. I have not yet proven it but I believe that my serial read got only a partial read "!A" instead of the whole message for some reason. This is then being sent directly to the nmea0183out  of SignalK which goes unfiltered to Kplex. Kplex then sends that data back to SignalK unfiltered which seems to be getting dropped by the SignalK nmea parser but still forward back to nmea0183out which starts the cycle again.

@tkurki when an nmea message is received does it just get immediately pushed out of the nmea0183out port regardless of the parser?

**Closed by tkurki** 2020-09-03 15:38 UTC

**Comment by stripydog** [comment] 2020-09-03 15:51
Hopefully the fix you're testing will work out but be aware that it's based on the develop branch which contains other features which have not been thoroughly field tested.  If you have issues, or after your testing would rather go back to the stable version, sounds like adding in checksum checking would also work around this problem (but glad you found it thanks! and to Teppo for contacting me).

**Comment by TensionSoftware** [comment] 2020-09-03 15:52
Noted and thank you both for your continued hard work!

**Comment by tkurki** [comment] 2020-09-03 16:09
Yes, nmea0183 input lines are spat out as nmea0183 data with no parsing involved.

**Comment by TensionSoftware** [comment] 2020-09-03 16:23
That is what I thought was happening. Makes sense and thank you again.
