### ISSUE TITLE
Websocket stream subscription gets closed always after 60 seconds 

### ISSUE THREAD

**Issue by jeronimo** [SignalK/signalk-server#1409] opened 2022-02-23 03:17 UTC
Made a separate connection to double check it is on the server side:
`const ws = new WebSocket('ws://<signalk.local>/signalk/v1/stream?serverevents=all&subscribe=none&sendMeta=all')`
and it always closes connection after 60 seconds which causes to reload the whole signalk webpage.

<img width="664" alt="Screenshot 2022-02-22 at 22 12 07" src="https://user-images.githubusercontent.com/88912/155256224-77cac117-5ad3-4351-b32f-016fdcd51af8.png">

**Comment by sbender9** [comment] 2022-02-23 04:05
Unsure of the context here...But my guess would be that you are not reading from the socket. The server will close the connection in that case.

**Comment by jeronimo** [comment] 2022-02-23 04:18
> Unsure of the context here...But my guess would be that you are not reading from the socket. The server will close the connection in that case.

Sorry, probably went too deep while trying to debug myself.
The code and bellow
https://github.com/SignalK/signalk-server/blob/master/packages/server-admin-ui/src/actions.js#L162
is causing admin UI to reload. But I am guessing it is on server side as it always closes after 61 seconds.

**Comment by sbender9** [comment] 2022-02-23 04:48
The admin ui will reload if the ws connection closes. That is by design. 

The question is why is it closing? 

This is definitely not happening for me. 

Anything interesting in the server log?

**Comment by sbender9** [comment] 2022-02-23 04:53
Wondering... Are you running this in the normal way (npm -g installed package), or are doing something different/unconventional?

**Comment by tkurki** [comment] 2022-02-23 05:47
Do you have security enabled?

**Comment by jeronimo** [comment] 2022-02-23 12:09
Thank you guys for such great respond, you made me think about different causes. The issue is somewhere in `avahi-alias` or `lighttpd` as that reload does not happen through direct `http://ip:port` access.

**Comment by tkurki** [comment] 2022-02-23 12:39
Feel free to reopen if needed.

**Closed** 2022-02-23 12:39 UTC
