### ISSUE TITLE
Improve Windows installation experience

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server#899] opened 2019-11-23 19:45 UTC
There are no clear installation instructions like we have to RPi, so maybe we could create some documentation. 

Furthermore the postinstall script is broken since v1.18.0 and throws an error when trying to detect tsc existence, leaving the user with a seemingly failed installation.

**Comment by tkurki** [comment] 2019-11-23 20:00
I think the easiest fix is to just remove the `postinstall` script, as very few will install the server from git and not figure out the build step.

**Comment by canne** [comment] 2019-11-23 20:10
Hi, sorry for not reporting this earlier, since sometime ago, I got warning, on Win 10, node.js v12.13.0 npm 6.5.0 update request from the GUI. Update from the command line using this product's installation information. Got the failure message. Did not realize that it was a success! I renamed the .signalk directory in my home folder to something else and tried again. No error message I was able to continue my work. Copied the few files I needed from the backup .signalk directory to the new one  and I was back in business. Thanks for the great, stable product!

**Comment by canne** [comment] 2019-11-23 20:13
BTW, if you can test the installation and upgrade on a Mac, that would be an asset!

**Comment by canne** [comment] 2019-12-22 12:36
For memo, and in meanwhile, I created a [startup script for Windows](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#startup_batch_file_script) and figured out how to [restart the dead service by surveying node.exe with a PowerShell script](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#automatic_restart_using_periodic_tasks). Not very elegant but works. (_systemd_ is not particularly aesthetic, either!)

**Comment by Charliepsycho** [comment] 2020-02-13 13:36
Wow, I've been a programmer for 25 years and I've never seen anything as bad as Signal K documentation!
It's not like what it is doing is hard, but using Node.JS? Only documenting an install to Raspberry PI?
By the way, none of the links to OpenCPN work.

**Comment by tkurki** [comment] 2020-02-13 14:55
Thank you for your kind words. Now how would you like to help?

**Comment by Charliepsycho** [comment] 2020-02-13 15:19
I wish I new. I have a suspicious feeling I am going to have to learn how Node.js and npm work first... which is a bit of a steep learning curve if you are only dabbling (and I don't really like these faddy frameworks)
Bear in mind I work as a Solution Architect creating ETL feeds from 1hz data. So I'm pretty used to this stuff and very tempted to write something to read the serial stream in c# and poke it out a webservice, but if someone has done it already then I'll try it. Ideally I want to log this stuff to a cloud server for some OOB analytics, probably in Power BI.
Any chance we can start a Windows guide to get Server-node running?
1) Install Node.js from https://nodejs.org/en/download/ (use the .msi installer for 32bit or 64bit depending on your version of Windows)
2) Install SignalK
Open a command line and type: npm install -g --unsafe-perm signalk-server
3) Start the SignalK Server  <-- I am stuck here!!
4) Navigate to the Signal K Server using your favorite browser to check it's running
http:////localhost:3000 <-- Probably ???
5) Configure some incoming data <-- NMEA 0183/2000/TCP
6) Look at some data coming out <-- Easy browser query
7) Try one of the instruments <-- Either one of the plugins, which may be a good intro or how to install one in IIS/apache etc
When doing a guide, assume a really picky idiot is going to use it!

**Comment by canne** [comment] 2020-02-13 19:59
@Charliepsycho, please feel free to copy parts youf find useful in https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#native_nodejs_on_windows_10 into your submission here.

**Comment by tkurki** [comment] 2020-02-14 08:47
If you guys could come up with steps on how to install, start and make the server start automatically and include screenshots it would be absolutely wonderful!

Everything that is platform independent, like from step 5 above and after it, should be in some common _How to Get Started_ doc.

**Comment by tkurki** [comment] 2020-02-14 08:48
>Start the SignalK Server <-- I am stuck here!!

Doesn't `signalk-server` work on the command line after installation?

**Comment by canne** [comment] 2020-02-14 09:14
Automatic start on Win 10 here: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#automatic_start_on_login

**Comment by Charliepsycho** [comment] 2020-02-14 10:09
Going back to basics, I've reinstalled Node.JS.
Then run the NPM install
`npm install -g --unsafe-perm signalk-server`
With delightful error logs that basically say wrong version of Node.JS
`notsup Unsupported engine for signalk-server@1.22.0: wanted: {"node":"10"} (current: {"node":"12.15.0","npm":"6.13.7"})`
So I've gone back to version 10 of node.js which fails on the install on signalk-server with
`189 error Unexpected end of JSON input while parsing near '...rl":"~1.0.1","escape-'`
sigh... maybe I'll try a docker image!

**Comment by canne** [comment] 2020-02-14 10:39
I've just installed 1.22.0 on 12.16.0 LTS node.js on Win 10 a couple of days ago. No issues. Don't worry about the error messages for the lowest node.js needed - if you can run signalk-server from command line, you're done, have you tried to run it?

Upgrading from a node.js versions that old... I would not trust its uninstaller and I would clean the old installation manually from your app directory as before installing the current node.js LTS version. Make sure that you do not have anything that even remotely says node.js or signalk anywhere in your home directory after the uninstall, including the app Roaming. Reboot to clean any changes in PATH that could still point to v10 and then start the latest node.js LTS installation from scratch.

If you get this error: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#caveat_1 **that** may be a killer for your futur plans if they consist to use some CAN hardware adapter. Not sure though, since I am all network based on Windows and have my hardware on Linux.

Docker, of course, is the easiest way to go for just trying things out when network based, see here: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:signalk:a3#signal_k_node_server_for_nodejs_as_docker-image .

**Comment by Charliepsycho** [comment] 2020-02-14 10:47
Nah, if I try to run signalk-server I get no file found error
`c:\>signalk-server
'signalk-server' is not recognized as an internal or external command,
operable program or batch file.`
So my guess is it has not installed

**Comment by canne** [comment] 2020-02-14 10:51
Alright, please try the above and report back the results, For example, what is the PATH. Normally, when you open the CMD window one is in the home directory,  not in C:\ so just wondering. Anyway, when back to my home computer I can show you a few screenshots how things are there.

**Comment by Charliepsycho** [comment] 2020-02-14 10:56
`PATH=C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\CharlesPhillips\AppData\Local\Microsoft\WindowsApps;C:\Users\CharlesPhillips\AppData\Roaming\npm`

I dumped out to c:\ to avoid oddities in my profile.

**Comment by Charliepsycho** [comment] 2020-02-14 11:36
Yeah, I did check the program files for Node stuff. Amusing that it is putting stuff in the profile of the person that installed it as well, very quaint.
I'm going to do a clean-up and uninstall everything. I wonder what it has done to the registry!
It has to be said... NodeJS is definitely not ready for prime time!

**Comment by canne** [comment] 2020-02-14 12:57
Node.js is an open source project so if they would have clumsy or evil intentions regarding your registry, that would have been known. PATH mods are required since it is a ubiquitous server platform not a Windows application. Launching applications needs to occur from user's command prompt (or from batch file).

Anyway, JavaScript server run-time philosophy is not the point here: if you want to run SignalK server on Windows, it is possible for me, so it should be possible for you, let's see:

You have ...\Roaming\npm in your path, that's a good sign . If you have installed node.js LTS from scratch and Signal K on top of it you should find a script signalk-server from your path. Can you please check what's in those npm-directories in Roaming, also in directory named npm*cache-something. No need to dump the contents here though: do you see anything named 'signalk' or 'signalk-server' in the directory which is enumerated in you PATH environment variable?

If that not the case, one mistake that can happen is that your packages are installed elsewhere, like in your home directory, in `node_modules` directory. One can check the path where the "-g" option puts the files, type `npm list -g | head -1` for that. They should be in `%USERPROFILE%\AppData\Roaming\npm\node_modules` on Win 10.

You can take a look what has been actually installed with `npm list -g --depth=0`

Can't see `signalk-server`? Well, try something that should work out of the box then, even on Windows: `npm -g install http-server`. Then check again the above list to see if it is installed and known by the package manager. Then try to launch it from the command line, just `http-server`. If it cannot be found, the PATH is not pointing into right directory.

This can be caused by installing, uninstalling old versions, not rebooting in between (it is the current session PATH). Stick to LTS of node.js, no reason to move back and worth: the npm is doing the package version control OK.

Let me know how you are doing with this. If needed, I can later join here some screenshots as Teppo suggested.

**Comment by canne** [comment] 2020-02-14 21:05
@Charliepsycho  & others Windows _node.js_ users, before sending here the screenshots I promised to @tkurki, a word to correct the perception that _node.js_ (actually _npm_) global scope has something to do with the Windows all-users scope:

_node.js_ and _npm_ are addressing both a developer, having multiple node projects going on and the need to have a run-time environment for the development nodes. In both cases, they are serving as a run-time JavaScript standalone service platform. For example, I am authoring books using the excellent _TiddlyWiki_ node server in global scope, while I am developing a browser JavaScript project in another folder in my home directory, in local scope.

Therefore, _node.js_ is not a Windows application for all users but a framework for the command-line use which installs in your directory. There is a way to build a CI (Continuous Integration) service for all users of a Windows server but that discussion is out of scope of this thread.

From the above follows that one would use _npm_ (Node Package Manager's) option `npm install -g`  to install in the global scope the applications executed from the command prompt. The GUI is created (or not) by the application, like by the `signalk-server`, on a browser.

For completeness sake (but not a necessary-to-know information to use _signalk-server_): a developer installs packages in a local scope, by moving to the directory where the development takes place and uses the _npm_ option `--save` to install node modules which shall go the end product he or she is developing and `--save-dev` to install node modules which are only used during the development process. Many local scopes can exists (many developments) but only one global scope exists.

**Comment by canne** [comment] 2020-02-14 21:08
node.js (LTS) and npm version on a Windows 10 Pro version 1909 installed on 2/9/2020 OS-build 18363.657
<img width="346" alt="nodejs_npm_versions" src="https://user-images.githubusercontent.com/6381128/74567662-8b4c7380-4f76-11ea-87a4-a9452f98b54a.png">

**Comment by canne** [comment] 2020-02-14 21:10
Command 
<img width="945" alt="PATH" src="https://user-images.githubusercontent.com/6381128/74567744-bfc02f80-4f76-11ea-9dc6-d7cf34c054b4.png">
execution path for cmd and PowerShell

**Comment by canne** [comment] 2020-02-14 21:11
Clean start from scratch
<img width="518" alt="npm_no_global_modules" src="https://user-images.githubusercontent.com/6381128/74567827-f138fb00-4f76-11ea-921e-d9fb26e2d227.png">

**Comment by canne** [comment] 2020-02-14 21:12
Installing latest signalk-server (as for now, v1.22.0)
<img width="443" alt="npm_install_signalk-server_latest_cmd" src="https://user-images.githubusercontent.com/6381128/74567881-0dd53300-4f77-11ea-914e-e35a12adc1f5.png">

**Comment by canne** [comment] 2020-02-14 21:14
Checking that there's something in the PATH:
<img width="379" alt="check_PATH_launch_signalk-server_cmd" src="https://user-images.githubusercontent.com/6381128/74568025-6278ae00-4f77-11ea-986e-887f6a4c7b0d.png">
Looks good!

**Comment by canne** [comment] 2020-02-14 21:19
Check that the Signal K node server is well there:
<img width="398" alt="browser_connect_to_signalk-server" src="https://user-images.githubusercontent.com/6381128/74568182-b5526580-4f77-11ea-90c3-71fb4fb48f81.png">
What happens in the command line, meanwhile?
<img width="440" alt="browser_connect_to_signalk-server_cmd-out" src="https://user-images.githubusercontent.com/6381128/74568215-c4d1ae80-4f77-11ea-9bf0-8bd7ee920bfc.png">
Stop the service:
<img width="255" alt="browser_connect_to_signalk-server_cmd-stop" src="https://user-images.githubusercontent.com/6381128/74568250-d7e47e80-4f77-11ea-9ba1-ad47acd49b57.png">
Can't really call this a difficult, but I am biased since doing this every day.

**Comment by canne** [comment] 2020-02-14 21:23
For @tkurki : I decided to roll back to v1.21.0 for my development since I saw this:
<img width="435" alt="npm_list_global_modules_signalk-server_v1-22-0" src="https://user-images.githubusercontent.com/6381128/74568447-4d504f00-4f78-11ea-9b55-ad071f4f917d.png">
I reckon that is not a big deal for an end user but since I am in middle of something I prefer to have v1.21.0:
<img width="236" alt="npm_list_global_modules_signalk-server_v1-21-0" src="https://user-images.githubusercontent.com/6381128/74568531-7b359380-4f78-11ea-829a-7ae658f46382.png">
[npm-list_signalk-server_v1-21-0.txt](https://github.com/SignalK/signalk-server-node/files/4206874/npm-list_signalk-server_v1-21-0.txt)

Hope this helps, I need to rush back to my project now! I'll keep listening this thread, of course

**Comment by tkurki** [comment] 2020-02-15 14:55
@canne thanks for reporting the peer dep thing. It is harmless, but another needless error message to confuse the installer. Fix is in #960.

**Comment by Charliepsycho** [comment] 2020-02-17 08:42
Finally, Success!
I had to wipe any previous reference to Node in my profile... And I installed on Node v12.15.0, but I can see the Signal K Website on Port 3000.
Now to do repeatable instructions...

**Comment by canne** [comment] 2020-02-17 08:54
Great job! Good to hear.

**Comment by Charliepsycho** [comment] 2020-02-24 11:21
So upon starting SignalK-Server I got the message:
`A new version (1.23.0) of the server is available`

A little bit of googling shows that npm has an update command which appears to have solved the update:
`npm update -g signalk-server`

Not sure if this has solved everything as it looks like a dependency is what has actually been changed:
`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

So I will have to look a bit deeper, but at least Signalk-server is running and I can continue to explore.

**Comment by cmotelet** [comment] 2020-04-14 18:07
FYI,
A new github repository has just been created with an Windows installer for Signal K server.
I'm looking for beta testers to try it out.
https://github.com/SignalK/signalk-server-windows/blob/master/readme.md

**Comment by canne** [comment] 2020-04-14 18:16
Great  job! 👍

**Closed** 2021-11-30 20:38 UTC
